# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  # Requiring a subpackage that contains Go code pulls in the whole
  # package.

  # For verify/update scripts
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/go-to-protobuf",
  "k8s.io/code-generator/cmd/go-to-protobuf/protoc-gen-gogo",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  # For verify scripts.
  "github.com/kubernetes/repo-infra/verify/boilerplate/test",
  # For k8s.io/apiserver/pkg/util/sets:set-gen
  "k8s.io/apimachinery/pkg/util/sets/types",
  "k8s.io/code-generator/cmd/set-gen",
]

ignored = [
  "github.com/kubernetes/repo-infra/kazel",
]

[[constraint]]
  name = "github.com/go-openapi/spec"
  revision = "84b5bee7bcb76f3d17bcbaf421bac44bd5709ca6"

[[constraint]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "k8s.io/api"
  revision = "218912509d74a117d05a718bb926d0948e531c20"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "18a564baac720819100827c16fdebcadb05b2d0d"

[[constraint]]
  name = "k8s.io/apiserver"
  revision = "3b8c9fae4af400f611953c44a72b66cf4cd6ca0d"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "dbe8fe09ed1682bc26b4e55cac5ef65dcd7664e9"


[[override]]
  name = "github.com/ugorji/go"
  revision = "d23841a297e5489e787e72fceffabf9d2994b52a"

[[override]]
  name = "google.golang.org/grpc"
  revision = "bfaf0423469fc4f95e9eac7e3eec0b2abb46fcca"

[[override]]
  name = "github.com/coreos/etcd"
  revision = "0520cb9304cb2385f7e72b8bc02d6e4d3257158a"

[[override]]
  name = "k8s.io/code-generator"
  revision = "dac22934f1bf35605309431df35132fc2811bc41"

[[override]]
  name = "github.com/kubernetes/repo-infra"
  revision = "0aafaab9e158d3628804242c6a9c4dd3eb8bce1f"

[[override]]
  name = "k8s.io/gengo"
  revision = "b6c426f7730e6d66e6e476a85d1c3eb7633880e0"

[[constraint]]
  branch = "master"
  name = "k8s.io/kube-aggregator"
